version = 1

[[analyzers]]
name = "javascript"
enabled = true

exclude_patterns = [
  "bin/**",
  "**/node_modules/",
  "js/*/*.min.js",
  ".vercel/**",
  ".next/**",
]

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "browser",
    "nodejs"
  ]
  dialect = "typescript"
